---
engines:
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
    config:
      extensions:
        - "*.js"
        - "*.html"

  duplication:
    enabled: true
    config:
      languages:
        - javascript

  fixme:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.html"
